spring:
  application:
    name: webhooks
  datasource:
    url: jdbc:h2:mem:webhooks
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:webhooks
    user: sa
    password:
    enabled: true
    locations: classpath:db/migrations

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true

stripe:
  secret: ${STRIPE_SECRET:1234567890}
